# site properties and page defaults
title: BioM2 Lab
subtitle: Biosphere Modeling and Monitoring
description: Advance predictive understanding of terrestrial biosphere dynamics through modeling and observations across ecological scales.
header: images/lab-website-background-top.jpg
footer: images/lab-website-background-bottom.jpg
proofer: false

domain: biom2-lab.github.io
url: https://biom2-lab.github.io
baseurl: /

# site social media and other links
links:
  email: xx286@cornell.edu
  orcid: 0000-0002-9402-9474
  google-scholar: fAorsowAAAAJ
  github: BioM2-Lab
  #twitter: YourLabHandle
  #youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post


collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
